#include "./defines.h"
#include "./camera.cpp"
#include "./render.cpp"
#include "./animation_action_enums.h"
#include "./animation.cpp"
#include "./entity.h"
#include "./map_tile.cpp"
#include "./game_state.h"
#include "./collision.cpp"
#include "./load_animations.cpp"
// #include "./player.cpp"
#include "./entity.cpp"
#include "./game_state.cpp"
